---
- name: create vm demo
  hosts: localhost
  become: false
  gather_facts: false

  pre_tasks:
    - include_vars: vars.yml
    - include_vars: vcenter_creds.yml

  tasks:
    - name: create folder
      community.vmware.vcenter_folder:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter_name: "{{ vcenter_datacenter }}"
        folder_name: "{{ vcenter_destination_folder }}"
        folder_type: vm
        state: present

    - name: create VM
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ vcenter_datacenter }}"
        name: "{{ vm_name }}"
        folder: "{{ vcenter_destination_folder }}"
        state: "{{ vm_state }}"
        guest_id: "{{ vm_guestid }}"
        cluster: "{{ vcenter_cluster }}"
        disk:
          - size_gb: "{{ vm_disk_gb }}"
            type: "{{ vm_disk_type }}"
            datastore: "{{ vm_disk_datastore }}"
        cdrom:
          - controller_number: 0
            unit_number: 0
            state: present
            type: iso
            iso_path: "[{{ vm_disk_datastore }}] CentOS-Stream-9-latest-x86_64-dvd1.iso"
        hardware:
          memory_mb: "{{ vm_hw_ram_mb }}"
          num_cpus: "{{ vm_hw_cpu_n }}"
          num_cpu_cores_per_socket: "{{vm_hw_cpu_cn}}"
          scsi: "{{ vm_hw_scsi }}"
        networks:
          - name: "{{ vm_net_name }}"
            device_name: "{{ vm_net_type }}"
            mac: "{{ vm_net_mac }}"
            ip: "{{ vm_net_ip }}"
      delegate_to: localhost

